    [[edge_functions]]
      path = "/properties/*"
      function = "property-preview"

    [[redirects]]
      from = "/*"
      to = "/index.html"
      status = 200

    [[headers]]
      for = "/assets/*"
      [headers.values]
        Cache-Control = "public, max-age=31536000, immutable"

    [[headers]]
      for = "/hero-carousel/*"
      [headers.values]
        Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"

    [[headers]]
      for = "/icon.png"
      [headers.values]
        Cache-Control = "public, max-age=604800, stale-while-revalidate=86400"

    [[headers]]
      for = "/index.html"
      [headers.values]
        Cache-Control = "public, max-age=0, must-revalidate"
